import type { Metadata } from "next";import {Poppins} from "next/font/google";
import "./globals.css";
import {NextFont} from "next/dist/compiled/@next/font";

import Header from "@/app/components/Header";
import ReduxProvider from "./components/StoreProvider";

const poppins: NextFont = Poppins({
  weight: ["100", "400", "500", "700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <html lang="en" className={poppins.className}>
        <body>
          <Header />
          <div className="container">
            {children}
          </div>
        </body>
      </html>
    </ReduxProvider>
  );
}
